package constants;

public enum UIEventType {
    EXTRACT_BUTTON_CLICK, PAUSE_BUTTON_CLICK, RESTART_BUTTON_CLICK, OPEN_FILE_BUTTON_CLICK,
    TIME_VALUE_CHANGE, RESTART_FROM_BEGINNING_OPTION_CHOSEN, RESTART_FROM_TIME_OPTION_CHOSEN
}
